/* Includes ------------------------------------------------------------------*/
#include "main.h" // Main header file generated by CubeMX (includes HAL drivers)
#include <string.h> // Added for memset usage

/* Private define ------------------------------------------------------------*/
// !!! IMPORTANT: Change to the I2C handle (Instance) configured in CubeMX.
// Example: If using I2C1, use hi2c1
#define I2C_HANDLE Hi2c1

// !!! IMPORTANT: Change to the 7-bit address of the slave device to communicate with.
// HAL functions internally handle the 8-bit address format (7-bit address + R/W bit),
// so use the 7-bit address left-shifted by 1 bit.
// Example: If slave address is 0x5A, use (0x5A << 1)
#define SLAVE_DEVICE_ADDRESS (0x5A << 1) // Example address (change to actual device address)

#define I2C_TIMEOUT_MS 100 // I2C communication timeout (in milliseconds)

/* Private variables ---------------------------------------------------------*/
// I2C handle variable defined by CubeMX in main.c (or elsewhere)
// Extern declaration to access this variable from main.cpp
extern I2C_HandleTypeDef Hi2c1; // Verify it matches I2C_HANDLE

/* Private function prototypes -----------------------------------------------*/
// Functions generated by CubeMX (SystemClock_Config, MX_GPIO_Init, MX_I2C1_Init, etc.)
// Declared in main.h

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config(); // Call clock configuration function generated by CubeMX

  /* Initialize all configured peripherals */
  MX_GPIO_Init();     // Call GPIO initialization function generated by CubeMX
  MX_I2C1_Init();     // Call I2C initialization function generated by CubeMX (must match I2C_HANDLE)

  /* Infinite loop */
  while (1)
  {
    HAL_StatusTypeDef Status;

    // 1. Check if slave device is ready (optional but recommended)
    //    Try 3 times with timeout of I2C_TIMEOUT_MS
    Status = HAL_I2C_IsDeviceReady(&I2C_HANDLE, SLAVE_DEVICE_ADDRESS, 3, I2C_TIMEOUT_MS);

    if (Status == HAL_OK)
    {
      // Device responded

      // 2. Data transmission (Master Transmit) example
      uint8_t TxData[] = {0x01, 0xAA, 0xBB}; // Example: Write 0xAA, 0xBB to register address 0x01
      uint16_t TxSize = sizeof(TxData);

      Status = HAL_I2C_Master_Transmit(&I2C_HANDLE,       // I2C handle
                                       SLAVE_DEVICE_ADDRESS, // Slave address
                                       TxData,             // Data buffer to send
                                       TxSize,             // Data size to send
                                       I2C_TIMEOUT_MS);    // Timeout

      if (Status == HAL_OK)
      {
        // Transmission successful
        // On success, can add desired actions like LED toggle
        HAL_Delay(10); // Short delay (not mandatory)
      }
      else
      {
        // Transmission failed
        Error_Handler();
      }

      // 3. Data reception (Master Receive) example
      uint8_t RxBuffer[10];              // Buffer to store received data
      uint16_t RxSize = 5;               // Example: Read 5 bytes
      memset(RxBuffer, 0, sizeof(RxBuffer)); // Initialize receive buffer

      // Before reading data, you often need to write the register address first (refer to device datasheet)
      // Example: If you want to read from register 0x05
      uint8_t RegAddr = 0x05;
      Status = HAL_I2C_Master_Transmit(&I2C_HANDLE, SLAVE_DEVICE_ADDRESS, &RegAddr, 1, I2C_TIMEOUT_MS);

      if(Status == HAL_OK)
      {
          // Attempt to read data after successfully writing register address
          Status = HAL_I2C_Master_Receive(&I2C_HANDLE,       // I2C handle
                                        SLAVE_DEVICE_ADDRESS, // Slave address
                                        RxBuffer,             // Receive data buffer
                                        RxSize,               // Data size to receive
                                        I2C_TIMEOUT_MS);      // Timeout

          if (Status == HAL_OK)
          {
            // Reception successful
            // Received data is stored in rxBuffer
            // Example: Output via UART or use for LED control
          }
          else
          {
            // Reception failed
            Error_Handler();
          }
      }
      else
      {
          // Register address write failed
          Error_Handler();
      }

    }
    else
    {
      // Device not responding or communication error
      // Add error handling logic (e.g., retry, error logging, etc.)
      // Error_Handler(); // Or other error handling approach
       HAL_Delay(500); // Wait briefly until device is ready
    }

    HAL_Delay(1000); // Wait 1 second then repeat
  }
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* Disable interrupts but allow watchdog to reset the system.
   * A fully dead loop with __disable_irq() leaves no recovery path
   * (watchdog won't fire, debugger may not attach). */
  while (1)
  {
    // Toggle LED to visually indicate error state
    // The watchdog (if configured) will eventually reset the MCU.
  }
}

#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  * where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void AssertFailed(uint8_t *File, uint32_t Line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
}
#endif /* USE_FULL_ASSERT */