version: '3'

services:
  opencv-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: opencv-fir-iir:latest
    container_name: opencv-fir-iir
    # X11 settings for GUI application
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    # Use host network (easy X11 access)
    network_mode: "host"
