version: '3'

services:
  mnist-train:
    build:
      context: .
      dockerfile: Dockerfile
    image: mnist-model:latest
    container_name: mnist-train
    environment:
      - MODE=train
      - CUDA_VISIBLE_DEVICES=""
    volumes:
      - ./models:/app/models
      - ./data:/app/data

  mnist-inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: mnist-model:latest
    container_name: mnist-inference
    environment:
      - MODE=inference
      - IMAGE_PATH=5.png
      - CUDA_VISIBLE_DEVICES=""
    volumes:
      - ./:/app
